/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariosReportes;

import clases.Conexion;
import clases.ErrorTienda;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author oscar
 */
public class frmComprasReportes extends javax.swing.JFrame {

    /**
     * Creates new form frmComprasReportes
     */
    public frmComprasReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btngTipos = new javax.swing.ButtonGroup();
        rbtnFactura = new javax.swing.JRadioButton();
        rbtnCredito = new javax.swing.JRadioButton();
        btnGenerarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btngTipos.add(rbtnFactura);
        rbtnFactura.setText("COMPRAS FACTURA, LIBRES");
        getContentPane().add(rbtnFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 91, -1, -1));

        btngTipos.add(rbtnCredito);
        rbtnCredito.setText("COMPRAS CREDITO FISCAL");
        rbtnCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCreditoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 91, -1, -1));

        btnGenerarReporte.setText("GENERAR REPORTE");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 204, 271, 74));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCreditoActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        
        if (rbtnCredito.isSelected()) {
            try {
            // TODO add your handling code here:
            Conexion cn = new Conexion();
            JasperReport reportecompras = JasperCompileManager.compileReport("comprasCredito.jrxml");
                JasperPrint print = JasperFillManager.fillReport(reportecompras, null, cn.conexion);
                JasperViewer view = new JasperViewer (print,false);
                view.setVisible(true);
        } catch (ErrorTienda ex) {
            Logger.getLogger(frmComprasReportes.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (JRException ex) {
                Logger.getLogger(frmComprasReportes.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        try {
            if (rbtnFactura.isSelected()) {
             Conexion cn = new Conexion();
            JasperReport reportecomprasLF = JasperCompileManager.compileReport("comprasLF.jrxml");
                JasperPrint print = JasperFillManager.fillReport(reportecomprasLF, null, cn.conexion);
                JasperViewer view = new JasperViewer (print,false);
                view.setVisible(true);
            
        }
            
        } catch (Exception e) {
        }
        
        

        
        
        
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmComprasReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmComprasReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmComprasReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmComprasReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmComprasReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.ButtonGroup btngTipos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rbtnCredito;
    private javax.swing.JRadioButton rbtnFactura;
    // End of variables declaration//GEN-END:variables
}
