/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.ControladorSucursal;
import clases.ControladorVenta;
import clases.ErrorTienda;
import clases.Sucursal;
import clases.Venta;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author jose-lopez
 */
public class frmVentasBorrador extends javax.swing.JFrame {

    /**
     * Creates new form frmVentasBorrador
     */
    JTableHeader ventas, detalles;
    DefaultTableModel modeloVentas, modeloDetalles;
    ArrayList<Sucursal> sucursales = new ArrayList();
    Object miSucursal[][];
    ResultSet rs = null;
    ControladorVenta cv = new ControladorVenta();
    
    
    
    public frmVentasBorrador() throws ErrorTienda, SQLException {
        initComponents();
        modeloVentas = (DefaultTableModel) tblVentasBorrador.getModel();
        modeloDetalles = (DefaultTableModel) tblDetallesVenta.getModel();
        CargarSucursales();
        CargarVentasBorrador("Todas", 12);
        
    }
    public void CabeceraTablas(){
        ventas = tblVentasBorrador.getTableHeader();
        detalles = tblDetallesVenta.getTableHeader();
        
        Font fuente = new Font("Tahoma", Font.BOLD, 12);
        ventas.setBackground(Color.red);
    }
    
    public void CargarVentasBorrador(String Criterio,int idSucursal) throws ErrorTienda, SQLException{
        Object[] fila=new Object[4];
        ArrayList<Venta> misventas;
        if(Criterio.equals("Todas")){
            misventas=ControladorVenta.VentasBorrador("TODAS", idSucursal);
        }else{
            misventas=ControladorVenta.VentasBorrador("PorSucursal", idSucursal);
        }
        
//            modeloDetalle.setColumnIdentifiers(campos);
            Iterator iterador=misventas.iterator();
            
            while (iterador.hasNext()) {
                fila[0]=iterador.next();
                fila[1]=iterador.next();
                fila[2]=iterador.next();
                fila[3]=false;
                
                modeloVentas.addRow(fila);
                
            }
       
    }
    public void CargarSucursales() throws ErrorTienda{
        sucursales = ControladorSucursal.obtener();
        miSucursal = new Object[sucursales.size()/4][4];
        
        int contador=0,fila=0;
        Iterator<Sucursal> iterador= sucursales.iterator();
        String temporal="";
        cmbSucursales.addItem("TODAS");
        while (iterador.hasNext()){
            miSucursal[fila][0]=iterador.next();
            miSucursal[fila][1]=iterador.next();
            miSucursal[fila][2]=iterador.next();
            miSucursal[fila][3]=iterador.next();
            cmbSucursales.addItem(""+miSucursal[fila][1]);
            fila++;
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpnBarra1 = new javax.swing.JPanel();
        lblBotonCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentasBorrador = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetallesVenta = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cmbSucursales = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jpnlConsolidarComo = new javax.swing.JPanel();
        jrbCredito = new javax.swing.JRadioButton();
        jrbFactura = new javax.swing.JRadioButton();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnBarra1.setBackground(new java.awt.Color(102, 0, 0));
        jpnBarra1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBotonCerrar.setBackground(new java.awt.Color(102, 0, 0));
        lblBotonCerrar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblBotonCerrar.setForeground(new java.awt.Color(102, 0, 0));
        lblBotonCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home/exit32.png"))); // NOI18N
        lblBotonCerrar.setToolTipText("Salir");
        lblBotonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonCerrarMouseClicked(evt);
            }
        });
        jpnBarra1.add(lblBotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 40, 50));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("Ventas en Borrador");
        jpnBarra1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        getContentPane().add(jpnBarra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        jLabel3.setText("Ventas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        tblVentasBorrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Venta", "Fecha", "Total", "Consolidar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVentasBorrador.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        tblVentasBorrador.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblVentasBorrador);
        if (tblVentasBorrador.getColumnModel().getColumnCount() > 0) {
            tblVentasBorrador.getColumnModel().getColumn(0).setResizable(false);
            tblVentasBorrador.getColumnModel().getColumn(1).setResizable(false);
            tblVentasBorrador.getColumnModel().getColumn(2).setResizable(false);
            tblVentasBorrador.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 340));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 10, 390));

        jLabel4.setText("Detalle de la venta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        tblDetallesVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodBarra", "Producto", "Cantidad", "Precio Unitario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetallesVenta.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblDetallesVenta);
        if (tblDetallesVenta.getColumnModel().getColumnCount() > 0) {
            tblDetallesVenta.getColumnModel().getColumn(0).setResizable(false);
            tblDetallesVenta.getColumnModel().getColumn(1).setResizable(false);
            tblDetallesVenta.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblDetallesVenta.getColumnModel().getColumn(2).setResizable(false);
            tblDetallesVenta.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 660, 340));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(cmbSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 350, -1));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sucursal:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, 40));

        jpnlConsolidarComo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consolidar como:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jpnlConsolidarComo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jrbCredito);
        jrbCredito.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jrbCredito.setText("Credito Fiscal");
        jpnlConsolidarComo.add(jrbCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        buttonGroup1.add(jrbFactura);
        jrbFactura.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jrbFactura.setSelected(true);
        jrbFactura.setText("Factura");
        jpnlConsolidarComo.add(jrbFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        getContentPane().add(jpnlConsolidarComo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 460, 130));

        btnContinuar.setText("Continuar");
        getContentPane().add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblBotonCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentasBorrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentasBorrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentasBorrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentasBorrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmVentasBorrador().setVisible(true);
                } catch (ErrorTienda ex) {
                    Logger.getLogger(frmVentasBorrador.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(frmVentasBorrador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbSucursales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpnBarra1;
    private javax.swing.JPanel jpnlConsolidarComo;
    private javax.swing.JRadioButton jrbCredito;
    private javax.swing.JRadioButton jrbFactura;
    public static javax.swing.JLabel lblBotonCerrar;
    private javax.swing.JTable tblDetallesVenta;
    private javax.swing.JTable tblVentasBorrador;
    // End of variables declaration//GEN-END:variables
}
